### ISSUE TITLE
this.name = 'syslog'; missing in npm version

### ISSUE THREAD

**Issue by hereandnow** [winstonjs/winston-syslog#11]
as the title says, this is missing in the npm-registry-version. could you just publish the current github master?

**Comment by magicpat** [comment]
Had the same headscratching moment too, when I realized that the github-version has a name, the NPM version doesn't ... and also it is not possible to manually set it afterwards, because of readonly-protection (which in my opinion is a terrible idea in JS :-) ).

If you just need the name for transport removal..try logger.remove({"name" : "syslog"}) instead. Works like a charm!

**Comment by santigimeno** [comment]
Fixed in https://github.com/winstonjs/winston-syslog/commit/2750b51b96520264d91f4e65993356e0de9fd679. It should be in the next published version

**Comment by magicpat** [comment]
Really cool to see this finally fixed :+1:
