### ISSUE TITLE
Call to this.socket.destroy crashes process

### ISSUE THREAD

**Issue by svencowart** [winstonjs/winston-syslog#121]
When this.socket.destroy is called a TypeError is thrown and crashes the process using the syslog transport.

After diagnosing the problem, I came to the following conclusion:
- Regardless the underlining socket implementation in use, this.socket.destroy is called on a timeout event.
- The dgram and unix-dgram modules do not include a socket.destroy method.
- Only the net module contains a socket.destroy method.

I opened this PR to get in the necessary changes:  https://github.com/winstonjs/winston-syslog/pull/120

**Comment by mempf** [comment]
Would be great to see this fixed. Also affected by it. Thanks for the PR.

**Comment by cjbarth** [comment]
The error I'm getting is on line [208](https://github.com/winstonjs/winston-syslog/blob/master/lib/winston-syslog.js#L208), so, while your PR does address part of this issue, it doesn't address all of it.

**Comment by svencowart** [comment]
@cjbarth this could be a different issue. Without further details, it is hard to know.

**Comment by cjbarth** [comment]
I'm looking into it myself right now and will provide more details when I have it.

**Comment by cjbarth** [comment]
Can anyone point to documentation that shows that a `socket` would have a `readyState` property? I can't find any. My limited testing also indicates that `socket.readyState` is always `undefined`. Thus, it seems that in all cases of timeout or closing, with `state.readyState` being `undefined`, `socket.destroy()` will be called.

However, it seems we should be checking for `socket.destroyed` and `socket.destroy` before calling `socket.destroy()`, perhaps instead of checking for `socket.readyState`.

**Comment by cjbarth** [comment]
I've created a PR to address the specific issues reported here and additional issues related to it that I've discovered in my investigation.

@DABH Does #115 look like the right approach to you?

**Comment by svencowart** [comment]
@cjbarth Thanks for the further investigation into this issue.  Looks great!

**Comment by DABH** [comment]
Closing this in favor of #122 , going to ship that out now!
